Ft project details
DjibrilM/Portfolio pull request #10
Opened 2023-05-16 16:20 UTC by DjibrilM

# In the following pull request i added 

- project detail modal

2023-05-16 21:54 UTC, brainconnect93 requested changes
## STATUS: Changes Required :recycle:

### Hi @DjibrilM, 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

### To Highlight :1st_place_medal: 

- Descriptive Pull Request title and summary. ✔️
- User clicks the button, the popup with details about the project appears ✔️
- User clicks the close (X) button, the popup disappears ✔️
- Modal popup data is populated with the data from the projects array ✔️
- Good use of Github flow ✔️

### Changes Required

- [ ] I would kindly suggest you work on the MIT license link of your project in the README file. Currently, the link is broken and throwing error 404. Basically i notice your project is missing the License file in the root directory kindly add it.

MIT 👇 

<img width="943" alt="mit" src="https://github.com/DjibrilM/Portfolio/assets/78634841/abbabfc7-69cf-455e-b29a-f8368362d9bd">


- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-16 21:54 UTC, brainconnect93 commented on assets/styles/details.css
> +}
- [ ] Great effort working on your pop up modal project, Currently i notice that the pop up card is hitting the wall of the page at the top and bottom which makes the `see live` and `see source` button get cut out, i would kindly suggest you work on it and be sure to have a design that looks like what we have in the Figma design

| Figma Design 👇 | Your Design 👇 |
| ------------- | ------------- |
| <img width="427" alt="real-pop" src="https://github.com/DjibrilM/Portfolio/assets/78634841/bd332c86-8c95-485e-bcee-89d4c5083e6d"> |<img width="948" alt="Nj" src="https://github.com/DjibrilM/Portfolio/assets/78634841/fa20081d-9316-413b-80ff-ecd8d0854333"> |

2023-05-16 21:54 UTC, brainconnect93 commented on index.html
> +                        <li>CANOPY</li>
- [ ] Hello @DjibrilM, As requested in this milestone, the pop up modal card should be created dynamically using `array of an object` in your JavaScript file and all the hardcoded line of codes in your HTML files should be removed

2023-05-16 21:54 UTC, brainconnect93 commented on index.html
>                  </div>
- [ ] Hello colleague, I could not highlight all the line of codes needed for this comment, but I would kindly advise you stick to the project requirement as much as possible, The goal of this milestone, is to have all your project cards that has been hardly coded in your HTML file be created dynamically in your JavaScript file using `array of an object`, Then all the line of code in your HTML file will be removed.

Below is the requirement 👇 

<img width="701" alt="image" src="https://github.com/DjibrilM/Portfolio/assets/78634841/eabd9edf-484a-4ab8-9924-deac038562cd">

2023-05-17 12:04 UTC, GedeonTS requested changes
# STATUS: CHANGES REQUIRED :recycle: :
Hi @DjibrilM , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif">

 ## Highlights :tophat: :+1: 
- No Linter Errors :100: 
- Meaningful Commit Messages :+1: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions :ringed_planet: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-17 14:38 UTC, AdnanOlarmmi approved these changes
Hi @DjibrilM,

This is Adnan Is-haq, your beloved code reviewer, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Approved office man](https://user-images.githubusercontent.com/41163571/219113922-5007d6bb-ff59-4916-b6d3-e5aad3cb4051.gif)

## Highlights
- Fixed changes.

## Optional suggestions
_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-17 15:08 UTC, merged