Add form validation to contact form
DjibrilM/Portfolio pull request #3
Opened 2023-05-02 08:57 UTC by DjibrilM

## Implement validation to contact form

  **In the following pull request I added**

   -  form validation to contact form

2023-05-02 09:15 UTC, Olamarx requested changes
Hi @DjibrilM, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have all the sections in the readme file filled. Kindly note that all the sections in the readme file are required except the FAQ so I will implore you to add them all before making a submission.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-02 09:51 UTC, DjibrilM commented
Thank you for the feedback but I don't see any section of README that I forgot to include, I think the README should only include features of the current, for example, the installation part. 
I can not add installation since this project is only built with HTML and CSS and there is nothing to install so no need to add <img src="https://media4.giphy.com/media/21I909B1Us5hsGiupn/giphy.gif"/>

2023-05-02 11:41 UTC, Ibizugbe reviewed
Hi @DjibrilM 👋👋,

![INVALID](https://user-images.githubusercontent.com/64643995/235654813-832b143b-7c15-41a9-831f-c9acd660afc0.gif)
 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Just as the previous reviewer have requested, You have submitted a project, that doesn't have the complete sections from the microverse readme template present🥲.  I understand your concerns but take a look at the suggestions below😉.

> The project is setup with linters hence you can "run `npm instal` " to get the dependencies for the various linters😉. that is valid for the install section👍.
> For the preiqusities section, kindly add what is needed to run the project👍.

> for the setup section, kindly state the process of cloning the project to your local computer👍.

In summary, I suggest you kindly follow the instructions in the [readme template](https://github.com/microverseinc/readme-template) and add a properly documented project with all sections added as the previous reviewer has requested👍.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-02 16:24 UTC, levy002 requested changes
## Hello @DjibrilM   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Highlights
- No linter error :heavy_check_mark: 

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [ ] Kindly make sure the `Contact` section contents are aligned on the page using the CSS `flexbox` in order to match the project requirement which will give you the ability to maintain the page responsiveness. 

- [ ] Kindly make sure to implement the `Get in touch` button interactions `(Active, hover, disabled, etc..)` styling.

    - ### BUTTON INTERACTION STYLING
    ![image](https://user-images.githubusercontent.com/87197412/235726320-d0f52fe9-8163-47b6-a69e-976b67b314b9.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-02 16:24 UTC, levy002 commented on index.html
> +                    <input id="email" name="email" required type="text" placeholder="Email">
- [ ] Kindly make sure your email `input`  has the `type="email"` instead of `type="text"` in order to match the project requirements.

2023-05-03 10:51 UTC, PinkMoon25 approved these changes
Hi @DjibrilM , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

## Highlights
Linters :heavy_check_mark: 
GitHub flow :heavy_check_mark: 
Changes Implemented :heavy_check_mark:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 11:03 UTC, merged