Implement desktop version
DjibrilM/Portfolio pull request #5
Opened 2023-05-04 09:01 UTC by DjibrilM

### In the following pull request I added 
- responsiveness for desktop screens

2023-05-04 11:40 UTC, usorfaitheloho requested changes
## Hi @DjibrilM   :clap:, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/rZ10JtoPRv1Ly/giphy.gif)

## To Highlight :clap:  
:arrow_forward: Followed the Figma design template :heavy_check_mark: 
:arrow_forward: Good code quality :heavy_check_mark: 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-04 11:40 UTC, usorfaitheloho commented on index.html
> +                <div class="contact-form-button-container">
Please use the right background color for the `hover` interaction of the `Get in touch` button of the `contact me` section to help you with a better UI : 

Button interaction :

![image](https://user-images.githubusercontent.com/20537712/236193226-1424b242-3001-4315-8632-88568688f8b7.png)

2023-05-04 15:49 UTC, Gambit142 reviewed
Hi @DjibrilM 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- You have submitted a project, that the GitHub actions can't carry out linters checks because of branch conflict. Kindly resolve the branch conflict and ensure that the linters actions run 👍

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-05 08:44 UTC, wickathou requested changes
Hi @DjibrilM  , 

## Great work on making the changes requested by a previous reviewer

# Just a few changes more and you will be done!

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 08:44 UTC, wickathou commented on index.html
> +                <h2>About Myself</h2>
- [ ] **Required:** As my colleague mentioned, your 'About Myself' font color and size must be:
`color: #091E42;`
`font-size: 40px;`

2023-05-05 08:44 UTC, wickathou commented on index.html
> +                        <path
- [ ] **Required:** As mentioned by my colleague, your 'About Myself' section is not arranged as shown on the figma file, as your are missing the 'LET's CONNECT' anchor tag and your `showcase-contact-icons` should be above the 'Get my resume' button

2023-05-05 08:44 UTC, wickathou commented on index.html
> +            </div>
- [ ] **Required:** You have the 'Frameworks' text repeated, when it must be 'Frameworks' and 'Skills', please update it as my colleague also mentioned

2023-05-05 08:44 UTC, wickathou commented on index.html
> +            </div>
[Optional] The `tools-summery` section should be a `ul` listing the 'Languagues', 'Frameworks' and 'Skills' with `li` elements which then contain their own `ul` and `li` elements to present their own lists

2023-05-05 11:30 UTC, amon-cofie approved these changes
Hi @DjibrilM , 👋 

Your project is complete and very impressive 💯!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights

🚀 You implemented changes requested by previous reviewers very well 
🚀 You have descriptive commit messages and you constructed them with imperative statements
🚀 You used GitHub flow properly
🚀 You have no linter errors


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 13:20 UTC, merged